<?php

declare(strict_types=1);

namespace Knot\Extension;

use Knot\Licensing\DolistoreValidator;
use Knot\Licensing\LicenseStatus;

/**
 * Validates extension licenses.
 *
 * V2.3.5 shipped a local-only validator: each commercial extension
 * needs a JSON licence file at `documents/knot/licenses/<id>.json`
 * (manually generated by the publisher and dropped on the server).
 *
 * V2.5.0a adds `validation = 'dolistore'`: the licence is checked
 * against the Knot licence backend with Ed25519-signed responses,
 * an instance binding and an offline grace window. The dolistore
 * branch is delegated to {@see \Knot\Licensing\DolistoreValidator}
 * — the constructor of this class accepts an optional injected
 * orchestrator (default: null, meaning the dolistore branch is not
 * available in the current runtime — typically because the manifest
 * does not require it).
 */
/**
 * V2.5.0b — `final` removed so test doubles (e.g. Pro Pack
 * ConnectorMigrationParityTest) can substitute a stub validator
 * without standing up a full Dolibarr stack. Production code MUST
 * still go through {@see \Knot\Licensing\Bootstrap::buildLicenseValidator()}.
 */
class LicenseValidator
{
    public const STATUS_VALID = 'valid';
    public const STATUS_MISSING = 'missing';
    public const STATUS_EXPIRED = 'expired';
    public const STATUS_INVALID = 'invalid';
    public const STATUS_TAMPERED = 'tampered';
    public const STATUS_NOT_REQUIRED = 'not_required';

    private string $licenseDir;
    private ?DolistoreValidator $dolistoreValidator;

    /**
     * @param string|null $licenseDir Override (defaults to documents/knot/licenses
     *                                using DOL_DATA_ROOT when available).
     * @param DolistoreValidator|null $dolistoreValidator Inject when the runtime
     *                                must support the dolistore validation mode.
     */
    public function __construct(
        ?string $licenseDir = null,
        ?DolistoreValidator $dolistoreValidator = null
    ) {
        if ($licenseDir !== null) {
            $this->licenseDir = rtrim($licenseDir, '/\\');
        } else {
            $base = defined('DOL_DATA_ROOT')
                ? (string) constant('DOL_DATA_ROOT')
                : sys_get_temp_dir();
            $this->licenseDir = $base . '/knot/licenses';
        }
        $this->dolistoreValidator = $dolistoreValidator;
    }

    /**
     * Inspect the license state for an extension manifest. Never throws.
     *
     * @param array<string, mixed> $manifest Normalised manifest (from ManifestSchema)
     * @return array{status: string, expiresAt: ?string, issuedTo: ?string, error: ?string}
     */
    public function inspect(array $manifest): array
    {
        $license = $manifest['license'] ?? [];
        $type = is_array($license) ? ($license['type'] ?? 'free') : 'free';
        $validation = is_array($license) ? ($license['validation'] ?? 'none') : 'none';

        if ($type === 'free' || $validation === 'none') {
            return [
                'status' => self::STATUS_NOT_REQUIRED,
                'expiresAt' => null,
                'issuedTo' => null,
                'error' => null,
            ];
        }

        $id = (string) ($manifest['id'] ?? '');

        if ($validation === 'dolistore') {
            if ($this->dolistoreValidator === null) {
                return [
                    'status' => self::STATUS_INVALID,
                    'expiresAt' => null,
                    'issuedTo' => null,
                    'error' => 'Dolistore validation requested but no DolistoreValidator wired in this runtime',
                ];
            }
            $resolved = $this->dolistoreValidator->inspect($manifest);
            return [
                'status' => $this->mapDolistoreStatus($resolved->status),
                'expiresAt' => $resolved->expiresAt,
                'issuedTo' => $resolved->issuedTo,
                'error' => $resolved->error,
            ];
        }

        $path = $this->licenseDir . '/' . $id . '.json';
        if (!is_readable($path)) {
            return [
                'status' => self::STATUS_MISSING,
                'expiresAt' => null,
                'issuedTo' => null,
                'error' => 'License file not found at ' . $path,
            ];
        }
        $raw = file_get_contents($path);
        if ($raw === false) {
            return [
                'status' => self::STATUS_INVALID,
                'expiresAt' => null,
                'issuedTo' => null,
                'error' => 'License file unreadable: ' . $path,
            ];
        }
        $data = json_decode($raw, true);
        if (!is_array($data)) {
            return [
                'status' => self::STATUS_INVALID,
                'expiresAt' => null,
                'issuedTo' => null,
                'error' => 'License file is not valid JSON',
            ];
        }
        $extId = (string) ($data['extensionId'] ?? '');
        if ($extId !== $id) {
            return [
                'status' => self::STATUS_INVALID,
                'expiresAt' => null,
                'issuedTo' => null,
                'error' => "License is for '$extId' but extension is '$id'",
            ];
        }
        $expiresAt = $data['expiresAt'] ?? null;
        if ($expiresAt !== null && $expiresAt !== '') {
            $expTs = strtotime((string) $expiresAt);
            if ($expTs === false) {
                return [
                    'status' => self::STATUS_INVALID,
                    'expiresAt' => null,
                    'issuedTo' => $data['issuedTo'] ?? null,
                    'error' => 'License expiresAt is not a valid date',
                ];
            }
            if ($expTs < time()) {
                return [
                    'status' => self::STATUS_EXPIRED,
                    'expiresAt' => date('c', $expTs),
                    'issuedTo' => $data['issuedTo'] ?? null,
                    'error' => 'License expired on ' . date('Y-m-d', $expTs),
                ];
            }
            $expiresIso = date('c', $expTs);
        } else {
            $expiresIso = null;
        }
        return [
            'status' => self::STATUS_VALID,
            'expiresAt' => $expiresIso,
            'issuedTo' => isset($data['issuedTo']) ? (string) $data['issuedTo'] : null,
            'error' => null,
        ];
    }

    /**
     * Hard gate used right before connector execute(). Throws when the
     * manifest declares a paid extension and the licence is missing/expired.
     *
     * @param array<string, mixed> $manifest
     * @throws \RuntimeException
     */
    public function ensureValid(array $manifest): void
    {
        $report = $this->inspect($manifest);
        if (
            in_array(
                $report['status'],
                [self::STATUS_VALID, self::STATUS_NOT_REQUIRED],
                true
            )
        ) {
            return;
        }
        $id = (string) ($manifest['id'] ?? '?');
        throw new \RuntimeException(
            sprintf(
                'Extension "%s" license check failed (%s): %s',
                $id,
                $report['status'],
                $report['error'] ?? 'unknown error'
            )
        );
    }

    public function getLicenseDir(): string
    {
        return $this->licenseDir;
    }

    private function mapDolistoreStatus(string $status): string
    {
        return match ($status) {
            LicenseStatus::VALID => self::STATUS_VALID,
            LicenseStatus::EXPIRED => self::STATUS_EXPIRED,
            LicenseStatus::MISSING => self::STATUS_MISSING,
            LicenseStatus::TAMPERED => self::STATUS_TAMPERED,
            LicenseStatus::NOT_REQUIRED => self::STATUS_NOT_REQUIRED,
            default => self::STATUS_INVALID,
        };
    }
}
