CREATE TABLE llx_knot_execution (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_workflow integer NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'queued',
  trigger_type varchar(64) NULL,
  trigger_data longtext NULL,
  started_at datetime NULL,
  ended_at datetime NULL,
  duration_ms integer NULL,
  error_message text NULL,
  error_payload text NULL,
  error_node_id varchar(128) NULL,
  retry_count integer NOT NULL DEFAULT 0,
  priority tinyint NOT NULL DEFAULT 5,
  scheduled_at datetime NULL,
  next_retry_at datetime NULL,
  max_attempts tinyint NOT NULL DEFAULT 3,
  worker_id varchar(36) NULL,
  backoff_strategy varchar(32) NOT NULL DEFAULT 'exponential',
  parent_execution_id integer NULL,
  entity integer NOT NULL DEFAULT 1,
  KEY idx_knot_execution_workflow_status (fk_workflow, status),
  KEY idx_knot_execution_entity_status (entity, status),
  KEY idx_knot_execution_entity_queue (entity, status, priority, scheduled_at, rowid),
  KEY idx_knot_execution_started_at (started_at),
  KEY idx_knot_execution_parent (parent_execution_id)
) ENGINE=innodb;
